disallowedblocks:
  exampleworld:
  - '7'
  - '19'
disallowedpickups:
  exampleworld:
  - '7'
  - '19'
bucket:
  disablelava: false
  lavaworld:
  - world
  disablewater: false
  waterworld:
  - world
pickupdelete: true
disableendereggteleport: true
deletewhenplaced: true
placemessage: '&cYou have insufficient permission to place that block.'
destroymessage: '&cYou have insufficient permission to destroy that block.'
