#Disallowed blocks that players cannot place or destroy
disallowedblocks:
  exampleworld:
  - '7'
  - '19'
#Disallowed items that cannot be picked up
disallowedpickups:
  exampleworld:
  - '7'
  - '19'
#Disallowed item tiles that cannot be dropped from the inventory
disalloweddrops:
  exampleworld:
  - '7'
  - '19'
#Lavaworld is where lava buckets are disabled and same goes for waterworld
bucket:
  lavaworld:
  - world
  waterworld:
  - world
#You cannot place or destroy anything in the worlds listed
#Use permissions for specific groups/people that you want to be able to build
disallowedworlds:
- exampleworld
#If true it deletes the disallowed pickup
pickupdelete: true
#If true when a player attempts to drop an item from the disalloweddrop list
#The item drop would then be deleted instead of being put back in the inventory
dropdelete: true
#If true it disables the ender egg from moving
disableendereggteleport: true
#If true it would delete the block on hand if it is disabled
deletewhenplaced: true
#If true then BlockControl would check for updates. It will not download updates
checkforupdates: true
#Messages to be shown when you have performed an action
placemessage: '&cYou have insufficient permission to place that block.'
destroymessage: '&cYou have insufficient permission to destroy that block.'
