name: BlockControl
version: 1.4.0
main: us.th3controller.blockcontrol.BlockControl
author: th3controller
commands:
   blockcontrol:
      description: BlockControl commands
      usage: /<command>
      aliases: bc
